# Generated by Django 5.2.15 on 2026-07-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="designation",
            field=models.CharField(
                choices=[
                    ("manager", "Manager"),
                    ("hr", "HR"),
                    ("tech_lead", "Technical Lead"),
                    ("team_lead_dev", "Team Lead"),
                    ("developer", "Software Developer"),
                    ("testing_lead", "Testing Lead"),
                    ("tester", "Testing Engineer"),
                    ("dm_lead", "Digital Marketing Lead"),
                    ("dm_exec", "Digital Marketing Executive"),
                    ("bd_exec", "Business Development Executive"),
                    ("intern", "Intern"),
                ],
                max_length=20,
            ),
        ),
    ]
